In [4]:
import random
random.randint(50,100)

99

In [1]:
import numpy as np
# 50學生,5個分數
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 65,  72,  60,  84,  93],
       [ 69, 100,  80,  96,  96],
       [ 50,  77,  54,  50,  68],
       [100,  75,  67,  73,  80],
       [ 94,  80,  89,  84,  70],
       [ 56,  92,  50,  55,  63],
       [ 59,  72,  51,  74,  72],
       [ 77,  77,  74,  97,  64],
       [ 85,  67,  54,  85,  60],
       [ 61,  74,  96,  97,  63],
       [ 97,  75,  57,  94,  84],
       [ 92,  62,  82,  57,  78],
       [ 69,  78,  69,  55,  51],
       [ 85,  59,  69,  65,  70],
       [ 57,  58,  65,  89, 100],
       [ 94,  72,  98,  61,  80],
       [ 88,  78,  67,  96,  75],
       [ 89,  71,  95,  57,  70],
       [ 64, 100,  74,  92,  65],
       [ 77,  65,  69,  50,  52],
       [ 75,  83,  73,  60,  75],
       [ 79,  87,  93,  50,  80],
       [ 62,  75,  84,  82,  83],
       [ 91,  63,  50,  53,  88],
       [ 55,  96,  78,  98,  67],
       [ 74,  68,  90,  94,  54],
       [ 67,  62,  60,  50,  78],
       [ 58,  80,  76,  64,  62],
       [ 92,  93,  75,  83,  92],
       [ 87,  

In [6]:
scores[0]

array([50, 83, 82, 57, 61])

In [7]:
scores[0:3]

array([[50, 83, 82, 57, 61],
       [84, 69, 89, 68, 79],
       [58, 73, 65, 98, 85]])

In [11]:
scores[0:20,3]

array([57, 68, 98, 50, 60, 81, 92, 82, 67, 96, 59, 52, 67, 76, 73, 73, 73,
       69, 95, 59])