In [30]:
import numpy as np
# 50學生,5個分數
scores = np.random.randint(50,101,size=(7,5))
scores

array([[71, 97, 73, 56, 80],
       [95, 89, 66, 81, 76],
       [67, 61, 88, 56, 59],
       [83, 79, 88, 81, 98],
       [68, 86, 64, 71, 60],
       [62, 51, 74, 75, 72],
       [65, 69, 94, 79, 90]])

In [10]:
#numpy 統計
np.sum(scores[2])
np.average(scores[3])

79.8

In [6]:
for i in scores:
    print(i)

[100  74  69  53  77]
[ 91 100  81  85  81]
[83 99 71 59 87]
[ 79 100  51  99  70]
[93 62 61 70 87]
[74 67 78 94 51]
[62 83 59 58 76]
[61 76 76 73 98]
[79 52 57 65 76]
[96 91 67 84 86]
[57 78 54 74 73]
[55 59 75 98 58]
[65 95 85 98 56]
[71 96 69 82 57]
[57 83 51 86 63]
[92 87 54 62 85]
[82 91 73 65 68]
[51 54 56 95 91]
[64 77 94 74 63]
[ 84  58  94 100  53]
[64 98 69 57 73]
[ 64  69  56 100  74]
[53 64 71 68 89]
[53 65 86 71 84]
[91 81 59 97 71]
[96 76 57 86 59]
[88 70 76 91 74]
[97 80 76 97 81]
[97 51 74 72 83]
[51 54 54 68 60]
[93 85 85 63 99]
[65 70 56 61 92]
[76 64 67 92 66]
[99 55 87 72 63]
[85 89 66 66 58]
[89 56 95 74 97]
[99 55 55 81 89]
[63 69 73 50 72]
[79 62 60 80 54]
[66 94 99 77 70]
[51 87 74 62 56]
[85 59 61 83 79]
[76 91 66 50 88]
[92 73 56 69 63]
[100  67  75  60  81]
[62 84 64 59 66]
[76 52 63 65 93]
[75 58 64 81 59]
[81 99 75 71 88]
[65 69 91 52 75]


In [7]:
scores.dtype

dtype('int64')

In [32]:
import pandas as pd

df = pd.DataFrame(data=scores,columns=['國文','英文','數學','地理','歷史'],index=['卡寶','余光中','瘂弦','濟慈','先勇','楊牧','海音'])
df

國文  英文  數學  地理  歷史
卡寶   71  97  73  56  80
余光中  95  89  66  81  76
瘂弦   67  61  88  56  59
濟慈   83  79  88  81  98
先勇   68  86  64  71  60
楊牧   62  51  74  75  72
海音   65  69  94  79  90

In [33]:
df.values

array([[71, 97, 73, 56, 80],
       [95, 89, 66, 81, 76],
       [67, 61, 88, 56, 59],
       [83, 79, 88, 81, 98],
       [68, 86, 64, 71, 60],
       [62, 51, 74, 75, 72],
       [65, 69, 94, 79, 90]])